# --------- SECTION GENERATED BY DOTFILE SCRIPT -------------
# https://github.com/meodbr/dotfiles

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

if [ -f ~/.config/shells/aliases.sh ]; then
    . ~/.config/shells/aliases.sh
fi

if [ -f ~/.config/shells/config.sh ]; then
    . ~/.config/shells/config.sh
fi

export PATH="$PATH:$HOME/.path:/snap/bin:$HOME/go/bin"

eval "$(starship init bash)"

